"""Initialize the Lab 26 database with reproducible schema and seed data."""

from __future__ import annotations

import argparse
import os
import sqlite3
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()


DEFAULT_SQLITE_PATH = Path(__file__).resolve().parent / "lab26.sqlite3"


SQLITE_SCHEMA_SQL = """
PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS enrollments;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS students;

CREATE TABLE students (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    cohort TEXT NOT NULL,
    score REAL NOT NULL CHECK (score >= 0 AND score <= 100),
    active INTEGER NOT NULL DEFAULT 1 CHECK (active IN (0, 1)),
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE courses (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    credits INTEGER NOT NULL CHECK (credits > 0)
);

CREATE TABLE enrollments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    student_id INTEGER NOT NULL,
    course_id INTEGER NOT NULL,
    term TEXT NOT NULL,
    grade REAL CHECK (grade IS NULL OR (grade >= 0 AND grade <= 100)),
    status TEXT NOT NULL DEFAULT 'enrolled' CHECK (status IN ('enrolled', 'completed', 'dropped')),
    UNIQUE (student_id, course_id, term),
    FOREIGN KEY (student_id) REFERENCES students(id) ON DELETE CASCADE,
    FOREIGN KEY (course_id) REFERENCES courses(id) ON DELETE CASCADE
);
"""


SQLITE_SEED_SQL = """
INSERT INTO students (name, email, cohort, score, active) VALUES
    ('John Smith', 'john@example.edu', 'A1', 96.5, 1),
    ('Jane Smith', 'jane@example.edu', 'A1', 93.0, 1),
    ('Jake Smith', 'jake@example.edu', 'B2', 98.0, 1),
    ('Alan Turing', 'alan@example.edu', 'B2', 91.0, 1),
    ('Mr Beast', 'mrbeast@example.edu', 'C3', 88.5, 0);

INSERT INTO courses (code, title, credits) VALUES
    ('MCP101', 'Model Context Protocol Basics', 3),
    ('DB201', 'Safe Database Tooling', 4),
    ('AI310', 'Agent Integration Studio', 3);

INSERT INTO enrollments (student_id, course_id, term, grade, status) VALUES
    (1, 1, '2026-SPRING', 97.0, 'completed'),
    (1, 2, '2026-SPRING', 95.0, 'completed'),
    (2, 1, '2026-SPRING', 94.0, 'completed'),
    (2, 3, '2026-SPRING', 92.0, 'completed'),
    (3, 2, '2026-SPRING', 99.0, 'completed'),
    (4, 1, '2026-SPRING', 90.0, 'completed'),
    (5, 3, '2026-SPRING', NULL, 'dropped');
"""


POSTGRES_SCHEMA_SQL = """
DROP TABLE IF EXISTS enrollments;
DROP TABLE IF EXISTS courses;
DROP TABLE IF EXISTS students;

CREATE TABLE students (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL UNIQUE,
    cohort TEXT NOT NULL,
    score DOUBLE PRECISION NOT NULL CHECK (score >= 0 AND score <= 100),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE courses (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    title TEXT NOT NULL,
    credits INTEGER NOT NULL CHECK (credits > 0)
);

CREATE TABLE enrollments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    student_id INTEGER NOT NULL REFERENCES students(id) ON DELETE CASCADE,
    course_id INTEGER NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
    term TEXT NOT NULL,
    grade DOUBLE PRECISION CHECK (grade IS NULL OR (grade >= 0 AND grade <= 100)),
    status TEXT NOT NULL DEFAULT 'enrolled' CHECK (status IN ('enrolled', 'completed', 'dropped')),
    UNIQUE (student_id, course_id, term)
);
"""


POSTGRES_SEED_SQL = """
INSERT INTO students (name, email, cohort, score, active) VALUES
    ('John Smith', 'john@example.edu', 'A1', 96.5, TRUE),
    ('Jane Smith', 'jane@example.edu', 'A1', 93.0, TRUE),
    ('Jake Smith', 'jake@example.edu', 'B2', 98.0, TRUE),
    ('Alan Turing', 'alan@example.edu', 'B2', 91.0, TRUE),
    ('Mr Beast', 'mrbeast@example.edu', 'C3', 88.5, FALSE);

INSERT INTO courses (code, title, credits) VALUES
    ('MCP101', 'Model Context Protocol Basics', 3),
    ('DB201', 'Safe Database Tooling', 4),
    ('AI310', 'Agent Integration Studio', 3);

INSERT INTO enrollments (student_id, course_id, term, grade, status) VALUES
    (1, 1, '2026-SPRING', 97.0, 'completed'),
    (1, 2, '2026-SPRING', 95.0, 'completed'),
    (2, 1, '2026-SPRING', 94.0, 'completed'),
    (2, 3, '2026-SPRING', 92.0, 'completed'),
    (3, 2, '2026-SPRING', 99.0, 'completed'),
    (4, 1, '2026-SPRING', 90.0, 'completed'),
    (5, 3, '2026-SPRING', NULL, 'dropped');
"""


def create_sqlite_database(database_path: str | Path | None = None) -> Path:
    """Create a fresh SQLite database and return its path."""

    path = Path(database_path or os.getenv("LAB26_DB_PATH") or DEFAULT_SQLITE_PATH)
    path.parent.mkdir(parents=True, exist_ok=True)
    with sqlite3.connect(path) as conn:
        conn.executescript(SQLITE_SCHEMA_SQL)
        conn.executescript(SQLITE_SEED_SQL)
        conn.commit()
    return path


def create_postgres_database(database_url: str | None = None) -> str:
    """Create a fresh PostgreSQL database using psycopg 3 and return its URL."""

    url = database_url or os.getenv("DATABASE_URL")
    if not url:
        raise RuntimeError("DATABASE_URL is required for PostgreSQL initialization")
    try:
        import psycopg
    except ImportError as exc:
        raise RuntimeError("PostgreSQL initialization requires: pip install 'psycopg[binary]>=3.2'") from exc

    with psycopg.connect(url) as conn:
        with conn.cursor() as cur:
            cur.execute(POSTGRES_SCHEMA_SQL)
            cur.execute(POSTGRES_SEED_SQL)
        conn.commit()
    return url


def create_database(backend: str | None = None) -> str:
    """Create the configured database and return the path or connection URL."""

    selected_backend = (backend or os.getenv("DB_BACKEND", "sqlite")).strip().lower()
    if selected_backend == "sqlite":
        return str(create_sqlite_database())
    if selected_backend in {"postgres", "postgresql"}:
        return create_postgres_database()
    raise RuntimeError("DB_BACKEND must be 'sqlite' or 'postgres'")


def main() -> None:
    parser = argparse.ArgumentParser(description="Initialize the Lab 26 database.")
    parser.add_argument("--backend", choices=["sqlite", "postgres"], default=os.getenv("DB_BACKEND", "sqlite"))
    parser.add_argument("--sqlite-path", default=os.getenv("LAB26_DB_PATH"), help="SQLite database path")
    args = parser.parse_args()

    if args.backend == "sqlite":
        path = create_sqlite_database(args.sqlite_path)
        print(f"SQLite database initialized at: {path}")
    else:
        url = create_postgres_database()
        print(f"PostgreSQL database initialized from DATABASE_URL: {url}")


if __name__ == "__main__":
    main()
